import { useState, type FormEvent } from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { LoaderCircle, LockKeyhole } from "@/components/ui/icons";
import { AuthShell } from "@/components/auth/auth-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/auth")({ head: () => ({ meta: [
  { title: "Connexion — Everest Distribution" }, { name: "description", content: "Connexion sécurisée à Everest Distribution." }, { property: "og:title", content: "Connexion — Everest Distribution" }, { property: "og:description", content: "Connexion sécurisée à la plateforme de gestion." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" },
] }), component: LoginPage });
function LoginPage() {
  const navigate = useNavigate(); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const form = new FormData(event.currentTarget); const { data, error: authError } = await supabase.auth.signInWithPassword({ email: String(form.get("email") ?? "").trim().toLowerCase(), password: String(form.get("password") ?? "") }); if (authError || !data.user) { setError("Email ou mot de passe incorrect, ou email non confirmé."); setLoading(false); return; } const { data: profile } = await supabase.from("profiles").select("statut").eq("id", data.user.id).single(); if (!profile || profile.statut !== "approved") { await supabase.auth.signOut(); await navigate({ to: "/en-attente", search: { statut: profile?.statut === "rejected" ? "rejected" : "pending" } }); return; } await navigate({ to: "/dashboard" }); }
  return <AuthShell><div className="bg-card px-6 py-8 shadow-sm sm:px-8"><span className="grid size-11 place-items-center rounded-md bg-brand-soft text-primary"><LockKeyhole className="size-6" /></span><h2 className="mt-5 text-3xl font-bold text-primary">Connexion</h2><p className="mt-2 text-sm text-muted-foreground">Accédez à votre espace selon le rôle qui vous a été accordé.</p><form className="mt-7 space-y-5" onSubmit={submit}><div className="space-y-2"><Label htmlFor="email">Adresse email</Label><Input id="email" name="email" type="email" autoComplete="email" required /></div><div className="space-y-2"><Label htmlFor="password">Mot de passe</Label><Input id="password" name="password" type="password" autoComplete="current-password" required /></div>{error && <p role="alert" className="border-l-2 border-danger bg-danger/5 px-3 py-2 text-sm text-danger">{error}</p>}<Button type="submit" size="lg" className="w-full bg-accent text-accent-foreground hover:bg-accent/90" disabled={loading}>{loading && <LoaderCircle className="animate-spin" />}Se connecter</Button></form><p className="mt-6 text-center text-sm text-muted-foreground">Pas encore de compte ? <Link to="/inscription" className="font-semibold text-primary hover:underline">Créer un compte</Link></p></div></AuthShell>;
}