import { createFileRoute, Link } from "@tanstack/react-router";
import { Clock3, XCircle } from "@/components/ui/icons";
import { z } from "zod";
import { AuthShell } from "@/components/auth/auth-shell";
import { Button } from "@/components/ui/button";
const searchSchema = z.object({ statut: z.enum(["pending", "rejected", "disabled"]).catch("pending") });
export const Route = createFileRoute("/en-attente")({ validateSearch: searchSchema, head: () => ({ meta: [
  { title: "Validation de l’accès — Everest Distribution" }, { name: "description", content: "État de la demande d’accès Everest Distribution." }, { property: "og:title", content: "Validation de l’accès — Everest Distribution" }, { property: "og:description", content: "Suivi de la demande d’accès à Everest Distribution." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" },
] }), component: PendingPage });
function PendingPage() { const { statut } = Route.useSearch(); const rejected = statut !== "pending"; const disabled = statut === "disabled"; const Icon = rejected ? XCircle : Clock3; return <AuthShell><div className="bg-card px-7 py-10 text-center shadow-sm"><Icon className={`mx-auto size-12 ${rejected ? "text-danger" : "text-warning"}`} /><h2 className="mt-5 text-2xl font-bold text-primary">{disabled ? "Compte désactivé" : rejected ? "Demande refusée" : "Accès en attente de validation"}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{disabled ? "Votre compte a été désactivé par l’administrateur. Contactez le PDG pour le réactiver." : rejected ? "Votre demande n’a pas été approuvée. Contactez le PDG pour obtenir plus d’informations." : "Votre email est confirmé, mais le PDG doit encore approuver votre rôle avant que vous puissiez accéder à l’application."}</p><Button asChild variant="outline" className="mt-7"><Link to="/auth">Retour à la connexion</Link></Button></div></AuthShell>; }