import { useEffect, useState, type FormEvent } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { CheckCircle2, LoaderCircle, UserPlus } from "@/components/ui/icons";
import { AuthShell } from "@/components/auth/auth-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { supabase } from "@/integrations/supabase/client";
type Centre = { id: string; nom: string };
export const Route = createFileRoute("/inscription")({ head: () => ({ meta: [
  { title: "Créer un compte — Everest Distribution" }, { name: "description", content: "Demandez un accès professionnel à Everest Distribution." }, { property: "og:title", content: "Créer un compte — Everest Distribution" }, { property: "og:description", content: "Demande d’accès à la plateforme Everest Distribution." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" },
] }), component: SignupPage });
function SignupPage() {
  const [role, setRole] = useState("gestionnaire_entrepot"); const [centreId, setCentreId] = useState(""); const [centres, setCentres] = useState<Centre[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [sent, setSent] = useState(false);
  useEffect(() => { void supabase.from("centres").select("id, nom").eq("actif", true).order("nom").then(({ data }) => setCentres(data ?? [])); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); if (role === "responsable_centre" && !centreId) { setError("Sélectionnez votre centre de vente."); return; } setLoading(true); const form = new FormData(event.currentTarget); const { error: signupError } = await supabase.auth.signUp({ email: String(form.get("email") ?? "").trim().toLowerCase(), password: String(form.get("password") ?? ""), options: { emailRedirectTo: window.location.origin + "/auth", data: { nom_complet: String(form.get("nom") ?? "").trim(), role_souhaite: role, centre_id: role === "responsable_centre" ? centreId : null } } }); if (signupError) { setError("L’inscription n’a pas pu être créée. Vérifiez les informations."); setLoading(false); return; } setSent(true); setLoading(false); }
  if (sent) return <AuthShell><div className="bg-card px-7 py-10 text-center shadow-sm"><CheckCircle2 className="mx-auto size-12 text-success" /><h2 className="mt-5 text-2xl font-bold text-primary">Confirmez votre email</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Cliquez sur le lien reçu par email. Votre accès restera ensuite en attente jusqu’à la validation du PDG.</p><Button asChild variant="outline" className="mt-7"><Link to="/auth">Retour à la connexion</Link></Button></div></AuthShell>;
  return <AuthShell><div className="bg-card px-6 py-8 shadow-sm sm:px-8"><span className="grid size-11 place-items-center rounded-md bg-brand-soft text-primary"><UserPlus className="size-6" /></span><h2 className="mt-5 text-3xl font-bold text-primary">Créer un compte</h2><p className="mt-2 text-sm text-muted-foreground">Votre demande devra être validée par le PDG avant le premier accès.</p><form className="mt-7 space-y-4" onSubmit={submit}><div className="space-y-2"><Label htmlFor="nom">Nom complet</Label><Input id="nom" name="nom" required /></div><div className="space-y-2"><Label htmlFor="email">Adresse email</Label><Input id="email" name="email" type="email" autoComplete="email" required /></div><div className="space-y-2"><Label htmlFor="password">Mot de passe</Label><Input id="password" name="password" type="password" autoComplete="new-password" minLength={8} required /><p className="text-xs text-muted-foreground">8 caractères minimum.</p></div><div className="space-y-2"><Label>Rôle souhaité</Label><Select value={role} onValueChange={(value) => { setRole(value); setCentreId(""); }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="gestionnaire_entrepot">Gestionnaire d’entrepôt</SelectItem><SelectItem value="responsable_centre" disabled={centres.length === 0}>Responsable de centre de vente</SelectItem></SelectContent></Select></div>{role === "responsable_centre" && <div className="space-y-2"><Label>Centre de vente</Label><Select value={centreId} onValueChange={setCentreId}><SelectTrigger><SelectValue placeholder="Sélectionner un centre" /></SelectTrigger><SelectContent>{centres.map((centre) => <SelectItem value={centre.id} key={centre.id}>{centre.nom}</SelectItem>)}</SelectContent></Select></div>}{centres.length === 0 && <p className="border-l-2 border-warning bg-warning/5 px-3 py-2 text-xs text-muted-foreground">Aucun centre n’est encore disponible. Le PDG doit d’abord en créer un.</p>}{error && <p role="alert" className="border-l-2 border-danger bg-danger/5 px-3 py-2 text-sm text-danger">{error}</p>}<Button type="submit" size="lg" className="w-full bg-accent text-accent-foreground hover:bg-accent/90" disabled={loading}>{loading && <LoaderCircle className="animate-spin" />}Envoyer ma demande</Button></form><p className="mt-6 text-center text-sm text-muted-foreground">Déjà inscrit ? <Link to="/auth" className="font-semibold text-primary hover:underline">Se connecter</Link></p></div></AuthShell>;
}