import { useEffect, useState } from "react";
import { createFileRoute, Link, redirect } from "@tanstack/react-router";
import { Check, LoaderCircle, UserCheck, X } from "@/components/ui/icons";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { supabase } from "@/integrations/supabase/client";
type PendingProfile = { id: string; nom_complet: string; email: string; role_souhaite: "admin" | "gestionnaire_entrepot" | "responsable_centre"; centre_id: string | null; created_at: string };
export const Route = createFileRoute("/_authenticated/admin/utilisateurs")({ beforeLoad: ({ context }) => { if (!context.roles.includes("admin")) throw redirect({ to: "/dashboard" }); }, head: () => ({ meta: [ { title: "Utilisateurs en attente — Everest Distribution" }, { name: "description", content: "Validation des demandes d’accès à Everest Distribution." }, { property: "og:title", content: "Utilisateurs en attente — Everest Distribution" }, { property: "og:description", content: "Administration sécurisée des demandes d’accès." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" } ] }), component: PendingUsersPage });
function PendingUsersPage() {
  const [users, setUsers] = useState<PendingProfile[]>([]); const [loading, setLoading] = useState(true); const [acting, setActing] = useState<string | null>(null); const [error, setError] = useState("");
  useEffect(() => { void supabase.from("profiles").select("id, nom_complet, email, role_souhaite, centre_id, created_at").eq("statut", "pending").order("created_at").then(({ data, error: loadError }) => { if (loadError) setError("Impossible de charger les demandes."); else setUsers(data ?? []); setLoading(false); }); }, []);
  async function review(id: string, approve: boolean) { setActing(id); const { error: reviewError } = await supabase.rpc("review_registration", { _user_id: id, _approve: approve }); if (reviewError) setError("La demande n’a pas pu être traitée."); else setUsers((current) => current.filter((user) => user.id !== id)); setActing(null); }
  return <main className="min-h-screen bg-background px-4 py-8 sm:px-8"><div className="mx-auto max-w-5xl"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-accent">ADMINISTRATION</p><h1 className="mt-1 text-3xl font-bold text-primary">Utilisateurs en attente</h1><p className="mt-2 text-sm text-muted-foreground">Approuvez uniquement les personnes et fonctions que vous reconnaissez.</p></div><Button asChild variant="outline"><Link to="/dashboard">Tableau de bord</Link></Button></div>{error && <p role="alert" className="mt-6 border-l-2 border-danger bg-danger/5 px-3 py-2 text-sm text-danger">{error}</p>}{loading ? <div className="grid min-h-56 place-items-center"><LoaderCircle className="size-7 animate-spin text-primary" /></div> : users.length === 0 ? <div className="mt-10 grid min-h-64 place-items-center border border-dashed bg-card text-center"><div><UserCheck className="mx-auto size-10 text-success" /><h2 className="mt-4 text-xl font-semibold text-primary">Aucune demande en attente</h2><p className="mt-1 text-sm text-muted-foreground">Toutes les inscriptions ont été traitées.</p></div></div> : <section className="mt-8 grid gap-4">{users.map((user) => <Card key={user.id}><CardContent className="grid gap-5 p-5 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-sans text-base font-semibold text-primary">{user.nom_complet}</h2><Badge variant="secondary">{user.role_souhaite === "responsable_centre" ? "Responsable de centre" : "Gestionnaire d’entrepôt"}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{user.email}</p></div><div className="flex gap-2"><Button variant="outline" className="text-danger" disabled={acting === user.id} onClick={() => void review(user.id, false)}><X /> Refuser</Button><Button className="bg-success text-primary-foreground hover:bg-success/90" disabled={acting === user.id} onClick={() => void review(user.id, true)}>{acting === user.id ? <LoaderCircle className="animate-spin" /> : <Check />} Approuver</Button></div></CardContent></Card>)}</section>}</div></main>;
}