/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EnAttenteRouteImport } from './routes/en-attente'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as AuthenticatedCentresRouteImport } from './routes/_authenticated/centres'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMouvementsRouteImport } from './routes/_authenticated/mouvements'
import { Route as AuthenticatedProduitsRouteImport } from './routes/_authenticated/produits'
import { Route as AuthenticatedRapportsRouteImport } from './routes/_authenticated/rapports'
import { Route as AuthenticatedReapprovisionnementRouteImport } from './routes/_authenticated/reapprovisionnement'
import { Route as AuthenticatedStocksRouteImport } from './routes/_authenticated/stocks'
import { Route as AuthenticatedAdminJournalRouteImport } from './routes/_authenticated/admin/journal'
import { Route as AuthenticatedAdminParametresRouteImport } from './routes/_authenticated/admin/parametres'
import { Route as AuthenticatedAdminUtilisateursRouteImport } from './routes/_authenticated/admin/utilisateurs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAttenteRoute = EnAttenteRouteImport.update({
  id: '/en-attente',
  path: '/en-attente',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCentresRoute = AuthenticatedCentresRouteImport.update({
  id: '/centres',
  path: '/centres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMouvementsRoute = AuthenticatedMouvementsRouteImport.update({
  id: '/mouvements',
  path: '/mouvements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProduitsRoute = AuthenticatedProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRapportsRoute = AuthenticatedRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReapprovisionnementRoute =
  AuthenticatedReapprovisionnementRouteImport.update({
    id: '/reapprovisionnement',
    path: '/reapprovisionnement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStocksRoute = AuthenticatedStocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminJournalRoute =
  AuthenticatedAdminJournalRouteImport.update({
    id: '/admin/journal',
    path: '/admin/journal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminParametresRoute =
  AuthenticatedAdminParametresRouteImport.update({
    id: '/admin/parametres',
    path: '/admin/parametres',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUtilisateursRoute =
  AuthenticatedAdminUtilisateursRouteImport.update({
    id: '/admin/utilisateurs',
    path: '/admin/utilisateurs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/en-attente': typeof EnAttenteRoute
  '/inscription': typeof InscriptionRoute
  '/centres': typeof AuthenticatedCentresRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mouvements': typeof AuthenticatedMouvementsRoute
  '/produits': typeof AuthenticatedProduitsRoute
  '/rapports': typeof AuthenticatedRapportsRoute
  '/reapprovisionnement': typeof AuthenticatedReapprovisionnementRoute
  '/stocks': typeof AuthenticatedStocksRoute
  '/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/en-attente': typeof EnAttenteRoute
  '/inscription': typeof InscriptionRoute
  '/centres': typeof AuthenticatedCentresRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mouvements': typeof AuthenticatedMouvementsRoute
  '/produits': typeof AuthenticatedProduitsRoute
  '/rapports': typeof AuthenticatedRapportsRoute
  '/reapprovisionnement': typeof AuthenticatedReapprovisionnementRoute
  '/stocks': typeof AuthenticatedStocksRoute
  '/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/en-attente': typeof EnAttenteRoute
  '/inscription': typeof InscriptionRoute
  '/_authenticated/centres': typeof AuthenticatedCentresRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/mouvements': typeof AuthenticatedMouvementsRoute
  '/_authenticated/produits': typeof AuthenticatedProduitsRoute
  '/_authenticated/rapports': typeof AuthenticatedRapportsRoute
  '/_authenticated/reapprovisionnement': typeof AuthenticatedReapprovisionnementRoute
  '/_authenticated/stocks': typeof AuthenticatedStocksRoute
  '/_authenticated/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/_authenticated/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/_authenticated/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/en-attente'
    | '/inscription'
    | '/centres'
    | '/dashboard'
    | '/mouvements'
    | '/produits'
    | '/rapports'
    | '/reapprovisionnement'
    | '/stocks'
    | '/admin/journal'
    | '/admin/parametres'
    | '/admin/utilisateurs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/en-attente'
    | '/inscription'
    | '/centres'
    | '/dashboard'
    | '/mouvements'
    | '/produits'
    | '/rapports'
    | '/reapprovisionnement'
    | '/stocks'
    | '/admin/journal'
    | '/admin/parametres'
    | '/admin/utilisateurs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/en-attente'
    | '/inscription'
    | '/_authenticated/centres'
    | '/_authenticated/dashboard'
    | '/_authenticated/mouvements'
    | '/_authenticated/produits'
    | '/_authenticated/rapports'
    | '/_authenticated/reapprovisionnement'
    | '/_authenticated/stocks'
    | '/_authenticated/admin/journal'
    | '/_authenticated/admin/parametres'
    | '/_authenticated/admin/utilisateurs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EnAttenteRoute: typeof EnAttenteRoute
  InscriptionRoute: typeof InscriptionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en-attente': {
      id: '/en-attente'
      path: '/en-attente'
      fullPath: '/en-attente'
      preLoaderRoute: typeof EnAttenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/centres': {
      id: '/_authenticated/centres'
      path: '/centres'
      fullPath: '/centres'
      preLoaderRoute: typeof AuthenticatedCentresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mouvements': {
      id: '/_authenticated/mouvements'
      path: '/mouvements'
      fullPath: '/mouvements'
      preLoaderRoute: typeof AuthenticatedMouvementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produits': {
      id: '/_authenticated/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof AuthenticatedProduitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rapports': {
      id: '/_authenticated/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof AuthenticatedRapportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reapprovisionnement': {
      id: '/_authenticated/reapprovisionnement'
      path: '/reapprovisionnement'
      fullPath: '/reapprovisionnement'
      preLoaderRoute: typeof AuthenticatedReapprovisionnementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stocks': {
      id: '/_authenticated/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof AuthenticatedStocksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/journal': {
      id: '/_authenticated/admin/journal'
      path: '/admin/journal'
      fullPath: '/admin/journal'
      preLoaderRoute: typeof AuthenticatedAdminJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/parametres': {
      id: '/_authenticated/admin/parametres'
      path: '/admin/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AuthenticatedAdminParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/utilisateurs': {
      id: '/_authenticated/admin/utilisateurs'
      path: '/admin/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AuthenticatedAdminUtilisateursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCentresRoute: typeof AuthenticatedCentresRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMouvementsRoute: typeof AuthenticatedMouvementsRoute
  AuthenticatedProduitsRoute: typeof AuthenticatedProduitsRoute
  AuthenticatedRapportsRoute: typeof AuthenticatedRapportsRoute
  AuthenticatedReapprovisionnementRoute: typeof AuthenticatedReapprovisionnementRoute
  AuthenticatedStocksRoute: typeof AuthenticatedStocksRoute
  AuthenticatedAdminJournalRoute: typeof AuthenticatedAdminJournalRoute
  AuthenticatedAdminParametresRoute: typeof AuthenticatedAdminParametresRoute
  AuthenticatedAdminUtilisateursRoute: typeof AuthenticatedAdminUtilisateursRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCentresRoute: AuthenticatedCentresRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMouvementsRoute: AuthenticatedMouvementsRoute,
  AuthenticatedProduitsRoute: AuthenticatedProduitsRoute,
  AuthenticatedRapportsRoute: AuthenticatedRapportsRoute,
  AuthenticatedReapprovisionnementRoute: AuthenticatedReapprovisionnementRoute,
  AuthenticatedStocksRoute: AuthenticatedStocksRoute,
  AuthenticatedAdminJournalRoute: AuthenticatedAdminJournalRoute,
  AuthenticatedAdminParametresRoute: AuthenticatedAdminParametresRoute,
  AuthenticatedAdminUtilisateursRoute: AuthenticatedAdminUtilisateursRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EnAttenteRoute: EnAttenteRoute,
  InscriptionRoute: InscriptionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
